jobs:
- name: deploy-github-changes
  plan:
  - aggregate:
    - get: pgr301-h18-devops-org
      trigger: true
  - task: apply
    file: pgr301-h18-devops-org/concourse/tasks/terraform/task.yml
    input_mapping: {source: pgr301-h18-devops-org}
    params:
      github_token: ((github_token))
      command: apply
      directories: |
          .

resources:

- name: pgr301-h18-devops-org
  type: git
  source:
    uri: git@github.com:grdall/pgr301-h18-devops-org.git
    branch: master
